# Generated by Django 4.2.7 on 2023-12-03 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serviciosAPI', '0001_initial'),
        ('reservasAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_metodoPago',
            fields=[
                ('codigo_mP', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo del metodo de pago')),
                ('tipo_mP', models.CharField(max_length=70, verbose_name='Tipo de metodo de pago')),
            ],
        ),
        migrations.CreateModel(
            name='tb_factura',
            fields=[
                ('codigo_fac', models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo de la factura')),
                ('fechaEmision_fac', models.DateField(verbose_name='Fecha de emision de la factura')),
                ('valorTotal_fac', models.FloatField(verbose_name='Valor total de la factura')),
                ('codigo_mP', models.ManyToManyField(to='facturasAPI.tb_metodopago', verbose_name='Metodos de pago')),
                ('codigo_res', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservasAPI.tb_reserva', verbose_name='Codigo de la Reserva')),
                ('numero_con', models.ManyToManyField(to='serviciosAPI.tb_consumo', verbose_name='Codigo consumo')),
            ],
        ),
    ]
