# Generated by Django 4.2.6 on 2023-12-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturasAPI', '0003_alter_tb_factura_codigo_fac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_factura',
            name='fechaEmision_fac',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de emision de la factura'),
        ),
    ]
