# Generated by Django 4.2.7 on 2023-12-03 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tb_rol',
            fields=[
                ('codigo_rl', models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo del rol')),
                ('tipo_rl', models.CharField(max_length=50, verbose_name='Tipo de rol')),
            ],
        ),
        migrations.CreateModel(
            name='tb_tpDocumento',
            fields=[
                ('codigo_tpD', models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo del tipo de documento')),
                ('tipo_tpDD', models.CharField(max_length=60, verbose_name='Tipo de documento')),
                ('abreviatura_tpD', models.CharField(max_length=50, verbose_name='Abreviatura del tipo de documento')),
            ],
        ),
        migrations.CreateModel(
            name='tb_usuarios',
            fields=[
                ('numeroDocumento_cli', models.CharField(default='', max_length=11, primary_key=True, serialize=False, verbose_name='Numero de Documento')),
                ('correoElectronico_clI', models.EmailField(default='', max_length=254, verbose_name='Correo Electronico')),
                ('nombres_cli', models.CharField(default='', max_length=50, verbose_name='Nombres Del usuario')),
                ('apellidos_cli', models.CharField(default='', max_length=50, verbose_name='Apellidos del usuario')),
                ('contrasena_cli', models.CharField(default='', max_length=50, verbose_name='Contraseña del usuario')),
                ('codigo_rl', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuariosAPI.tb_rol', verbose_name='Codigo de rol')),
                ('codigo_tpD', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuariosAPI.tb_tpdocumento', verbose_name='Codigo del tipo de documento')),
            ],
        ),
    ]
