# Generated by Django 4.2.7 on 2023-12-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuariosAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_rol',
            name='codigo_rl',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo del rol'),
        ),
        migrations.AlterField(
            model_name='tb_tpdocumento',
            name='codigo_tpD',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo del tipo de documento'),
        ),
    ]
