# Generated by Django 4.2.7 on 2023-12-04 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuariosAPI', '0002_alter_tb_rol_codigo_rl_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tb_usuarios',
            old_name='apellidos_cli',
            new_name='apellidos_usu',
        ),
        migrations.RenameField(
            model_name='tb_usuarios',
            old_name='contrasena_cli',
            new_name='contrasena_usu',
        ),
        migrations.RenameField(
            model_name='tb_usuarios',
            old_name='correoElectronico_clI',
            new_name='correoElectronico_usu',
        ),
        migrations.RenameField(
            model_name='tb_usuarios',
            old_name='nombres_cli',
            new_name='nombres_usu',
        ),
        migrations.RenameField(
            model_name='tb_usuarios',
            old_name='numeroDocumento_cli',
            new_name='numeroDocumento_usu',
        ),
    ]
