# Generated by Django 4.2.7 on 2024-04-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuariosAPI', '0003_rename_apellidos_cli_tb_usuarios_apellidos_usu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_usuarios',
            name='contrasena_usu',
        ),
        migrations.AddField(
            model_name='tb_usuarios',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='tb_usuarios',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='tb_usuarios',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='tb_usuarios',
            name='password',
            field=models.CharField(default='Contraseña del usuario', max_length=50, verbose_name='Contraseña del usuario'),
        ),
        migrations.AddField(
            model_name='tb_usuarios',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
