# Generated by Django 4.2.7 on 2024-04-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuariosAPI', '0005_tb_usuarios_contrasena_usu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_usuarios',
            name='contrasena_usu',
        ),
        migrations.AlterField(
            model_name='tb_usuarios',
            name='password',
            field=models.CharField(default='Contraseña del usuario', max_length=50, verbose_name='Contraseña del usuario'),
        ),
    ]
