# Generated by Django 4.2.7 on 2024-04-14 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuariosAPI', '0006_remove_tb_usuarios_contrasena_usu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tb_usuarios',
            old_name='correoElectronico_usu',
            new_name='email',
        ),
    ]
