# Generated by Django 4.2.7 on 2024-04-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuariosAPI', '0007_rename_correoelectronico_usu_tb_usuarios_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_usuarios',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tb_usuarios',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
