# Generated by Django 4.2.7 on 2024-04-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuariosAPI', '0008_tb_usuarios_is_active_tb_usuarios_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tb_usuarios',
            old_name='email',
            new_name='corroElectronico_usu',
        ),
        migrations.RemoveField(
            model_name='tb_usuarios',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='tb_usuarios',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='tb_usuarios',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='tb_usuarios',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='tb_usuarios',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='tb_usuarios',
            name='password',
        ),
        migrations.RemoveField(
            model_name='tb_usuarios',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='tb_usuarios',
            name='contrasena_usu',
            field=models.CharField(default='', max_length=50, verbose_name='Contraseña del usuario'),
        ),
    ]
