# Generated by Django 4.2.7 on 2024-04-15 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuariosAPI', '0009_rename_email_tb_usuarios_corroelectronico_usu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tb_usuarios',
            old_name='corroElectronico_usu',
            new_name='correoElectronico_usu',
        ),
    ]
