# Generated by Django 4.2.7 on 2023-12-03 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tb_estado',
            fields=[
                ('codigo_ed', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo del Estado')),
                ('tipo_ed', models.CharField(max_length=70, verbose_name='Tipo de Estado')),
            ],
        ),
        migrations.CreateModel(
            name='tb_paqueteMobiliario',
            fields=[
                ('codigo_pMb', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo del paquete')),
                ('paqueteTipo_pMb', models.CharField(max_length=70, verbose_name='Tipo de paquete')),
                ('camasSecillas_pMb', models.IntegerField(verbose_name='Numero de camas sencillas')),
                ('camasDobles_pMb', models.IntegerField(verbose_name='Numero de camas dobles')),
                ('camasTriples_pMb', models.IntegerField(verbose_name='Numero de camas triples')),
                ('numeroTelevisores_pMb', models.IntegerField(verbose_name='Numero de televisores')),
                ('numeroBanos_pMb', models.IntegerField(verbose_name='Numero de baños')),
                ('numeroToallas_pMb', models.IntegerField(verbose_name='Numero de toallas')),
                ('numeroTocadores', models.IntegerField(verbose_name='Numero de tocadores')),
            ],
        ),
        migrations.CreateModel(
            name='tb_tipoHabitacion',
            fields=[
                ('codigo_tpH', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo del tipo de habitacion')),
                ('tipo_tpH', models.CharField(max_length=70, verbose_name='Tipo de habitacion')),
                ('valorBase_tpH', models.FloatField(verbose_name='Valor base del tipo de habitacion')),
            ],
        ),
        migrations.CreateModel(
            name='tb_mobiliario',
            fields=[
                ('codigo_mB', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo del mobiliario')),
                ('codigo_pMb', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='habitacionesAPI.tb_paquetemobiliario', verbose_name='Codigo del paquete de mobiliario')),
                ('codigo_tpH', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='habitacionesAPI.tb_tipohabitacion', verbose_name='Codigo del tipo de habitacion')),
            ],
        ),
        migrations.CreateModel(
            name='tb_habitacion',
            fields=[
                ('codigo_hab', models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo de la habitacion')),
                ('descripcion_tpH', models.TextField(verbose_name='Descripcion de la habitacion')),
                ('minimoPersonas_tpH', models.IntegerField(verbose_name='Minimo de personas')),
                ('maximoPersonas_tpH', models.IntegerField(verbose_name='Maximo de personas')),
                ('image_tpH', models.ImageField(upload_to='media')),
                ('codigo_ed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitacionesAPI.tb_estado', verbose_name='Codigo del estado')),
                ('codigo_tpH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitacionesAPI.tb_tipohabitacion', verbose_name='Codigo del tipo de habitacion')),
            ],
        ),
    ]
