# Generated by Django 4.2.6 on 2023-12-06 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habitacionesAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_mobiliario',
            name='codigo_pMb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitacionesAPI.tb_paquetemobiliario', verbose_name='Codigo del paquete de mobiliario'),
        ),
        migrations.AlterField(
            model_name='tb_mobiliario',
            name='codigo_tpH',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitacionesAPI.tb_tipohabitacion', verbose_name='Codigo del tipo de habitacion'),
        ),
    ]
