# Generated by Django 4.2.6 on 2023-12-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_categoria',
            name='codigo_cat',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo de la categoria'),
        ),
    ]
