# Generated by Django 5.0.2 on 2024-03-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosAPI', '0002_alter_tb_categoria_codigo_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_consumo',
            name='fecha_con',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha del consumo'),
        ),
    ]
