# Generated by Django 4.2.7 on 2024-04-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasAPI', '0002_alter_tb_reserva_codigo_hab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_reserva',
            name='fechaInicio_res',
            field=models.DateTimeField(verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='tb_reserva',
            name='fechaSalida_res',
            field=models.DateTimeField(verbose_name='Fecha de salida'),
        ),
    ]
